config/routes.rb
RedmineApp::Application.routes.draw do
  resources :projects do
    resources :issue_reports, only: [:index, :create]
  end
end

app/controllers/issue_reports_controller.rb
class IssueReportsController < ApplicationController
  unloadable

  before_filter :find_project_by_project_id
  before_filter :authorize

  def index; end

  def create
    @results = RedmineIssueReport.summary(
      @project.id,
      params[:issue_reports_start_date],
      params[:issue_reports_due_date],
      params[:issue_reports_tracker]
    )

    @resolved_issues = issues_list('due_date', true)
    @resolved_details = RedmineIssueReport.details(@resolved_issues)

    @unresolved_issues = issues_list('start_date', false)
    @unresolved_details = RedmineIssueReport.details(@unresolved_issues)

    @config = RedmineIssueReportConfig.new

    render :index
  end

  private

  def issues_list(field, is_closed)
    RedmineIssueReport.list(
      field,
      is_closed,
      @project.id,
      params[:issue_reports_start_date],
      params[:issue_reports_due_date],
      params[:issue_reports_tracker]
    )
  end
end

app/helpers/issue_reports_helper.rb
module IssueReportsHelper
  def percent_format(value, total)
    value > 0 ? (value.to_f / total.to_f * 100).round : 0
  end
end

app/views/issue_reports/index.html.erb
<h2>Acompanhamento das ocorrências</h2>

<div class="box tabular">
  <%= form_tag project_issue_reports_path do %>
    <p>
      <%= label_tag(:issue_reports_tracker, "Tipo") %>
      <%= select_tag "issue_reports_tracker", options_from_collection_for_select(@project.trackers, "id", "name", params[:issue_reports_tracker]), include_blank: true %>
    </p>

    <p>
      <%= label_tag(:issue_reports_start_date, "Data inicial") %>
      <%= date_field_tag(:issue_reports_start_date, params[:issue_reports_start_date], size: 10, required: true) %>
    </p>

    <p>
      <%= label_tag(:issue_reports_due_date, "Data final") %>
      <%= date_field_tag(:issue_reports_due_date, params[:issue_reports_due_date], size: 10, required: true) %>
    </p>

    <p><%= submit_tag("Gerar relatório") %></p>
  <% end %>
</div>

<% if @results %>
  <div class="issues box">
    <h3>
      Acompanhamento das ocorrências - período de:
      <%= format_date(params[:issue_reports_start_date]) %>
      à
      <%= format_date(params[:issue_reports_due_date]) %>
    </h3>
    <table class="list issue-report">
      <thead>
        <tr>
          <th rowspan="2">Grau de severidade</th>
          <th colspan="2">Resolvidas</th>
          <th colspan="2">Não resolvidas</th>
          <th>Total</th>
        </tr>
        <tr>
          <th>Qtd.</th>
          <th>%</th>
          <th>Qtd.</th>
          <th>%</th>
          <th>Qtd.</th>
        </tr>
      </thead>
      <tbody>
      <%
        total_resolved, total_unresolved, grand_total = 0, 0, 0
        1.upto(@config.severity_number.to_i) do |occurrence|
          resolved = @results[occurrence]['resolved']
          unresolved = @results[occurrence]['unresolved']
          total = resolved + unresolved
          total_resolved += resolved
          total_unresolved += unresolved
          grand_total += total
      %>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= occurrence %></td>
          <td><%= resolved %></td>
          <td><%= percent_format(resolved, total) %></td>
          <td><%= unresolved %></td>
          <td><%= percent_format(unresolved, total) %></td>
          <td><%= total %></td>
        </tr>
      <% end %>
      </tbody>
      <tfoot>
        <tr>
          <th>Total</th>
          <th><%= total_resolved %></th>
          <th></th>
          <th><%= total_unresolved %></th>
          <th></th>
          <th><%= grand_total %></th>
        </tr>
      </tfoot>
    </table>
  </div>

  <% unless @resolved_issues.blank? %>
  <div class="issues box">
    <h3>Ocorrências resolvidas</h3>
    <table class="list issue-report">
      <thead>
        <tr>
          <th>Severidade</th>
          <th>Assunto</th>
          <th>Tipo</th>
          <th>Estado</th>
          <th>Abertura</th>
          <th>Encerramento</th>
          <th>Tempo decorrido (hs)</th>
        </tr>
      </thead>
      <tbody>
      <% @resolved_issues.each do |issue| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= issue.severity %></td>
          <td class="subject"><%= link_to issue.subject, issue_path(issue) %></td>
          <td><%= issue.tracker.name %></td>
          <td><%= issue.status %></td>
          <td><%= format_date(issue.created_on) %></td>
          <td><%= format_date(@resolved_details[:last_date][issue.id]) %></td>
          <td><%= @resolved_details[:hours][issue.id] %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <% end %>

  <% unless @unresolved_issues.blank? %>
  <div class="issues box">
    <h3>Ocorrências não resolvidas</h3>
    <table class="list issue-report">
      <thead>
        <tr>
          <th>Severidade</th>
          <th>Assunto</th>
          <th>Tipo</th>
          <th>Estado</th>
          <th>Abertura</th>
        </tr>
      </thead>
      <tbody>
      <% @unresolved_issues.each do |issue| %>
        <tr class="<%= cycle("odd", "even") %>">
          <td><%= issue.severity %></td>
          <td class="subject"><%= link_to issue.subject, issue_path(issue) %></td>
          <td><%= issue.tracker.name %></td>
          <td><%= issue.status %></td>
          <td><%= format_date(issue.created_on) %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
  <% end %>
<% end %>